### ISSUE TITLE
Configuration parameter to stop hiding category-menu on scrolling

### ISSUE THREAD

**Issue by Jayendra88** [vtex-apps/store-header#77]
**Is your feature request related to a problem? Please describe.**
Can't set category-menu to stay in header section while scrolling. 

**Describe the solution you'd like**
Add configuration parameter to stop hiding category-menu on scrolling.

**Comment by matheusps** [comment]
Hi @Jayendra88, 

You can control the animation aspects using the prop `collapsibleAnimation`, that has some default values.

You can check the docs @ section [**Collapsible Animation**](https://github.com/vtex-apps/store-header#configuration)

**Comment by Jayendra88** [comment]
Thank you very much @matheusps
